config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'maps#home'

  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :lat, :lng, presence: true
  validates :lat, :lng, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    respond_to do |format|
      format.json  { render :json => Photo.all}
    end
  end

  def new
    @photo = Photo.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    begin
      @photo = Photo.create(photo_params)
    rescue ArgumentError
      flash[:alert] = 'Invalid photo format'
    else
      if @photo.save
        flash[:notice] = 'Successfully added photo'
      else
        flash[:alert] = 'Unable to add photo'
      end
    ensure
      redirect_to :root
    end
  end

  private 
  def photo_params
    params.require(:photo).permit(:image,:lat, :lng)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlienEncounters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}"%>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>

  <body>
    <%= tag :meta, name: "api-key", content: ENV['GOOGLE_API_KEY'] %>
    <div class=".navbar-nav" id="navbar">
      <div class="logo"><%=image_tag("ufo.png", size: '40x40')%></div>
      <%= link_to "Add photo", new_photo_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>
      <div class="search">
        <form id="searchForm">
          <input type="text" id="seachTextbox" placeholder="Search Location.." name="search" required>
          <button type="submit" id="placeSearch"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notice"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/maps/home.html.erb
<div id="map"></div>
<!--   <div class="modal">
    <div class="modal-overlay modal-toggle"></div>
    <div class="modal-wrapper modal-transition">
      <div class="modal-close">&#10006;</div>
      <div class="modal-body">
        <div class="modal-content">
        </div>
      </div>
    </div>
  </div> -->

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/photos/_new.html.erb
<div class="modal-header">
   <h3 id="myModalLabel">Add Photo</h3>
</div>
<div class="modal-body">
  <div>
     <%= form_for @photo do |f| %>

        <table>
          <tbody>
           
            <tr>
              <td><label>Location</label></td>
              <td><%= text_field_tag 'location', nil, placeholder: 'Town, City, Postcode...', required: true%></td>
            </tr>
            <tr>
              <td><label>Photo</label></td>
              <td><%= f.file_field :image, required: true %></td>
            </tr>
          </tbody>
        </table> 
        <br>
        <table>
          <tbody>
            <tr>
              <td><button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button></td>
              <td><%= f.submit "Submit", class: "btn btn-primary", id: 'test'%></td>
            </tr>
          </tbody>
        </table>
        <%= f.hidden_field :lat, value: "" %>
        <%= f.hidden_field :lng, value: ""  %>
     <% end %>
  </div>
</div>

app/views/photos/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();